# SPDX-FileCopyrightText: 2024 Vincent DARON <vincent@ask.be>
# SPDX-License-Identifier: GPL-3.0-or-later

services:
   livecompose:
     image: askbe/livecompose:0.0.3
     environment:
      - ASK_LiveCompose__BasePath=/projects
      - ASK_LiveCompose__Key=123456456789
     volumes:
      - /home/flynn/Docker:/projects
      - /var/run/docker.sock:/var/run/docker.sock
     ports:
      - 9000:8080
     
