

services:
   composeapi:
     image: testcompose
     environment:
      - ASK_DockerComposeService__BasePath=/projects
      - ASK_DockerComposeService__Key=123456456789
     volumes:
      - /home/flynn/Docker:/projects
      - /var/run/docker.sock:/var/run/docker.sock
     ports:
      - 9000:8080
     
